// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrepo

import (
	"context"
	"github.com/google/uuid"
	"github.com/impactscope-organization/wobsongo/internal/data"
	"github.com/impactscope-organization/wobsongo/internal/model"
	"sync"
)

// Ensure, that AtomicKnowledgeRepoerMock does implement data.AtomicKnowledgeRepoer.
// If this is not the case, regenerate this file with moq.
var _ data.AtomicKnowledgeRepoer = &AtomicKnowledgeRepoerMock{}

// AtomicKnowledgeRepoerMock is a mock implementation of data.AtomicKnowledgeRepoer.
//
//	func TestSomethingThatUsesAtomicKnowledgeRepoer(t *testing.T) {
//
//		// make and configure a mocked data.AtomicKnowledgeRepoer
//		mockedAtomicKnowledgeRepoer := &AtomicKnowledgeRepoerMock{
//			CreateBatchFunc: func(ctx context.Context, knowledge []model.AtomicKnowledge) error {
//				panic("mock out the CreateBatch method")
//			},
//			MarkChunkKnowledgeExtractedFunc: func(ctx context.Context, chunkID uuid.UUID) error {
//				panic("mock out the MarkChunkKnowledgeExtracted method")
//			},
//			WithTxFunc: func(ctx context.Context, fn func(data.AtomicKnowledgeRepoer) error) error {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedAtomicKnowledgeRepoer in code that requires data.AtomicKnowledgeRepoer
//		// and then make assertions.
//
//	}
type AtomicKnowledgeRepoerMock struct {
	// CreateBatchFunc mocks the CreateBatch method.
	CreateBatchFunc func(ctx context.Context, knowledge []model.AtomicKnowledge) error

	// MarkChunkKnowledgeExtractedFunc mocks the MarkChunkKnowledgeExtracted method.
	MarkChunkKnowledgeExtractedFunc func(ctx context.Context, chunkID uuid.UUID) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(ctx context.Context, fn func(data.AtomicKnowledgeRepoer) error) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatch holds details about calls to the CreateBatch method.
		CreateBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Knowledge is the knowledge argument value.
			Knowledge []model.AtomicKnowledge
		}
		// MarkChunkKnowledgeExtracted holds details about calls to the MarkChunkKnowledgeExtracted method.
		MarkChunkKnowledgeExtracted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChunkID is the chunkID argument value.
			ChunkID uuid.UUID
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(data.AtomicKnowledgeRepoer) error
		}
	}
	lockCreateBatch                 sync.RWMutex
	lockMarkChunkKnowledgeExtracted sync.RWMutex
	lockWithTx                      sync.RWMutex
}

// CreateBatch calls CreateBatchFunc.
func (mock *AtomicKnowledgeRepoerMock) CreateBatch(ctx context.Context, knowledge []model.AtomicKnowledge) error {
	if mock.CreateBatchFunc == nil {
		panic("AtomicKnowledgeRepoerMock.CreateBatchFunc: method is nil but AtomicKnowledgeRepoer.CreateBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Knowledge []model.AtomicKnowledge
	}{
		Ctx:       ctx,
		Knowledge: knowledge,
	}
	mock.lockCreateBatch.Lock()
	mock.calls.CreateBatch = append(mock.calls.CreateBatch, callInfo)
	mock.lockCreateBatch.Unlock()
	return mock.CreateBatchFunc(ctx, knowledge)
}

// CreateBatchCalls gets all the calls that were made to CreateBatch.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.CreateBatchCalls())
func (mock *AtomicKnowledgeRepoerMock) CreateBatchCalls() []struct {
	Ctx       context.Context
	Knowledge []model.AtomicKnowledge
} {
	var calls []struct {
		Ctx       context.Context
		Knowledge []model.AtomicKnowledge
	}
	mock.lockCreateBatch.RLock()
	calls = mock.calls.CreateBatch
	mock.lockCreateBatch.RUnlock()
	return calls
}

// MarkChunkKnowledgeExtracted calls MarkChunkKnowledgeExtractedFunc.
func (mock *AtomicKnowledgeRepoerMock) MarkChunkKnowledgeExtracted(ctx context.Context, chunkID uuid.UUID) error {
	if mock.MarkChunkKnowledgeExtractedFunc == nil {
		panic("AtomicKnowledgeRepoerMock.MarkChunkKnowledgeExtractedFunc: method is nil but AtomicKnowledgeRepoer.MarkChunkKnowledgeExtracted was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChunkID uuid.UUID
	}{
		Ctx:     ctx,
		ChunkID: chunkID,
	}
	mock.lockMarkChunkKnowledgeExtracted.Lock()
	mock.calls.MarkChunkKnowledgeExtracted = append(mock.calls.MarkChunkKnowledgeExtracted, callInfo)
	mock.lockMarkChunkKnowledgeExtracted.Unlock()
	return mock.MarkChunkKnowledgeExtractedFunc(ctx, chunkID)
}

// MarkChunkKnowledgeExtractedCalls gets all the calls that were made to MarkChunkKnowledgeExtracted.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.MarkChunkKnowledgeExtractedCalls())
func (mock *AtomicKnowledgeRepoerMock) MarkChunkKnowledgeExtractedCalls() []struct {
	Ctx     context.Context
	ChunkID uuid.UUID
} {
	var calls []struct {
		Ctx     context.Context
		ChunkID uuid.UUID
	}
	mock.lockMarkChunkKnowledgeExtracted.RLock()
	calls = mock.calls.MarkChunkKnowledgeExtracted
	mock.lockMarkChunkKnowledgeExtracted.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *AtomicKnowledgeRepoerMock) WithTx(ctx context.Context, fn func(data.AtomicKnowledgeRepoer) error) error {
	if mock.WithTxFunc == nil {
		panic("AtomicKnowledgeRepoerMock.WithTxFunc: method is nil but AtomicKnowledgeRepoer.WithTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(data.AtomicKnowledgeRepoer) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(ctx, fn)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.WithTxCalls())
func (mock *AtomicKnowledgeRepoerMock) WithTxCalls() []struct {
	Ctx context.Context
	Fn  func(data.AtomicKnowledgeRepoer) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(data.AtomicKnowledgeRepoer) error
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
