// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrepo

import (
	"context"
	"github.com/google/uuid"
	"github.com/impactscope-organization/wobsongo/internal/data"
	"github.com/impactscope-organization/wobsongo/internal/model"
	"github.com/impactscope-organization/wobsongo/internal/queue"
	"sync"
)

// Ensure, that DocumentChunkRepoerMock does implement data.DocumentChunkRepoer.
// If this is not the case, regenerate this file with moq.
var _ data.DocumentChunkRepoer = &DocumentChunkRepoerMock{}

// DocumentChunkRepoerMock is a mock implementation of data.DocumentChunkRepoer.
//
//	func TestSomethingThatUsesDocumentChunkRepoer(t *testing.T) {
//
//		// make and configure a mocked data.DocumentChunkRepoer
//		mockedDocumentChunkRepoer := &DocumentChunkRepoerMock{
//			CreateBatchFunc: func(ctx context.Context, chunks []model.DocumentChunk) error {
//				panic("mock out the CreateBatch method")
//			},
//			EnqueueFunc: func(ctx context.Context, payload queue.BackgroundJob) error {
//				panic("mock out the Enqueue method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*model.DocumentChunk, error) {
//				panic("mock out the GetByID method")
//			},
//			ListByDocumentIDFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
//				panic("mock out the ListByDocumentID method")
//			},
//			ListChunksNeedingEmbeddingFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
//				panic("mock out the ListChunksNeedingEmbedding method")
//			},
//			ShouldBeStoredFunc: func(ctx context.Context, chunk model.DocumentChunk) (bool, error) {
//				panic("mock out the ShouldBeStored method")
//			},
//			UpdateFunc: func(ctx context.Context, chunk *model.DocumentChunk) error {
//				panic("mock out the Update method")
//			},
//			WithTxFunc: func(ctx context.Context, fn func(data.DocumentChunkRepoer) error) error {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedDocumentChunkRepoer in code that requires data.DocumentChunkRepoer
//		// and then make assertions.
//
//	}
type DocumentChunkRepoerMock struct {
	// CreateBatchFunc mocks the CreateBatch method.
	CreateBatchFunc func(ctx context.Context, chunks []model.DocumentChunk) error

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, payload queue.BackgroundJob) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*model.DocumentChunk, error)

	// ListByDocumentIDFunc mocks the ListByDocumentID method.
	ListByDocumentIDFunc func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error)

	// ListChunksNeedingEmbeddingFunc mocks the ListChunksNeedingEmbedding method.
	ListChunksNeedingEmbeddingFunc func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error)

	// ShouldBeStoredFunc mocks the ShouldBeStored method.
	ShouldBeStoredFunc func(ctx context.Context, chunk model.DocumentChunk) (bool, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, chunk *model.DocumentChunk) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(ctx context.Context, fn func(data.DocumentChunkRepoer) error) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatch holds details about calls to the CreateBatch method.
		CreateBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chunks is the chunks argument value.
			Chunks []model.DocumentChunk
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Payload is the payload argument value.
			Payload queue.BackgroundJob
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListByDocumentID holds details about calls to the ListByDocumentID method.
		ListByDocumentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// ListChunksNeedingEmbedding holds details about calls to the ListChunksNeedingEmbedding method.
		ListChunksNeedingEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// ShouldBeStored holds details about calls to the ShouldBeStored method.
		ShouldBeStored []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chunk is the chunk argument value.
			Chunk model.DocumentChunk
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chunk is the chunk argument value.
			Chunk *model.DocumentChunk
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(data.DocumentChunkRepoer) error
		}
	}
	lockCreateBatch                sync.RWMutex
	lockEnqueue                    sync.RWMutex
	lockGetByID                    sync.RWMutex
	lockListByDocumentID           sync.RWMutex
	lockListChunksNeedingEmbedding sync.RWMutex
	lockShouldBeStored             sync.RWMutex
	lockUpdate                     sync.RWMutex
	lockWithTx                     sync.RWMutex
}

// CreateBatch calls CreateBatchFunc.
func (mock *DocumentChunkRepoerMock) CreateBatch(ctx context.Context, chunks []model.DocumentChunk) error {
	if mock.CreateBatchFunc == nil {
		panic("DocumentChunkRepoerMock.CreateBatchFunc: method is nil but DocumentChunkRepoer.CreateBatch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Chunks []model.DocumentChunk
	}{
		Ctx:    ctx,
		Chunks: chunks,
	}
	mock.lockCreateBatch.Lock()
	mock.calls.CreateBatch = append(mock.calls.CreateBatch, callInfo)
	mock.lockCreateBatch.Unlock()
	return mock.CreateBatchFunc(ctx, chunks)
}

// CreateBatchCalls gets all the calls that were made to CreateBatch.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.CreateBatchCalls())
func (mock *DocumentChunkRepoerMock) CreateBatchCalls() []struct {
	Ctx    context.Context
	Chunks []model.DocumentChunk
} {
	var calls []struct {
		Ctx    context.Context
		Chunks []model.DocumentChunk
	}
	mock.lockCreateBatch.RLock()
	calls = mock.calls.CreateBatch
	mock.lockCreateBatch.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *DocumentChunkRepoerMock) Enqueue(ctx context.Context, payload queue.BackgroundJob) error {
	if mock.EnqueueFunc == nil {
		panic("DocumentChunkRepoerMock.EnqueueFunc: method is nil but DocumentChunkRepoer.Enqueue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Payload queue.BackgroundJob
	}{
		Ctx:     ctx,
		Payload: payload,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, payload)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.EnqueueCalls())
func (mock *DocumentChunkRepoerMock) EnqueueCalls() []struct {
	Ctx     context.Context
	Payload queue.BackgroundJob
} {
	var calls []struct {
		Ctx     context.Context
		Payload queue.BackgroundJob
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *DocumentChunkRepoerMock) GetByID(ctx context.Context, id uuid.UUID) (*model.DocumentChunk, error) {
	if mock.GetByIDFunc == nil {
		panic("DocumentChunkRepoerMock.GetByIDFunc: method is nil but DocumentChunkRepoer.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.GetByIDCalls())
func (mock *DocumentChunkRepoerMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// ListByDocumentID calls ListByDocumentIDFunc.
func (mock *DocumentChunkRepoerMock) ListByDocumentID(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
	if mock.ListByDocumentIDFunc == nil {
		panic("DocumentChunkRepoerMock.ListByDocumentIDFunc: method is nil but DocumentChunkRepoer.ListByDocumentID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListByDocumentID.Lock()
	mock.calls.ListByDocumentID = append(mock.calls.ListByDocumentID, callInfo)
	mock.lockListByDocumentID.Unlock()
	return mock.ListByDocumentIDFunc(ctx, documentID)
}

// ListByDocumentIDCalls gets all the calls that were made to ListByDocumentID.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListByDocumentIDCalls())
func (mock *DocumentChunkRepoerMock) ListByDocumentIDCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListByDocumentID.RLock()
	calls = mock.calls.ListByDocumentID
	mock.lockListByDocumentID.RUnlock()
	return calls
}

// ListChunksNeedingEmbedding calls ListChunksNeedingEmbeddingFunc.
func (mock *DocumentChunkRepoerMock) ListChunksNeedingEmbedding(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
	if mock.ListChunksNeedingEmbeddingFunc == nil {
		panic("DocumentChunkRepoerMock.ListChunksNeedingEmbeddingFunc: method is nil but DocumentChunkRepoer.ListChunksNeedingEmbedding was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListChunksNeedingEmbedding.Lock()
	mock.calls.ListChunksNeedingEmbedding = append(mock.calls.ListChunksNeedingEmbedding, callInfo)
	mock.lockListChunksNeedingEmbedding.Unlock()
	return mock.ListChunksNeedingEmbeddingFunc(ctx, documentID)
}

// ListChunksNeedingEmbeddingCalls gets all the calls that were made to ListChunksNeedingEmbedding.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListChunksNeedingEmbeddingCalls())
func (mock *DocumentChunkRepoerMock) ListChunksNeedingEmbeddingCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListChunksNeedingEmbedding.RLock()
	calls = mock.calls.ListChunksNeedingEmbedding
	mock.lockListChunksNeedingEmbedding.RUnlock()
	return calls
}

// ShouldBeStored calls ShouldBeStoredFunc.
func (mock *DocumentChunkRepoerMock) ShouldBeStored(ctx context.Context, chunk model.DocumentChunk) (bool, error) {
	if mock.ShouldBeStoredFunc == nil {
		panic("DocumentChunkRepoerMock.ShouldBeStoredFunc: method is nil but DocumentChunkRepoer.ShouldBeStored was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Chunk model.DocumentChunk
	}{
		Ctx:   ctx,
		Chunk: chunk,
	}
	mock.lockShouldBeStored.Lock()
	mock.calls.ShouldBeStored = append(mock.calls.ShouldBeStored, callInfo)
	mock.lockShouldBeStored.Unlock()
	return mock.ShouldBeStoredFunc(ctx, chunk)
}

// ShouldBeStoredCalls gets all the calls that were made to ShouldBeStored.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ShouldBeStoredCalls())
func (mock *DocumentChunkRepoerMock) ShouldBeStoredCalls() []struct {
	Ctx   context.Context
	Chunk model.DocumentChunk
} {
	var calls []struct {
		Ctx   context.Context
		Chunk model.DocumentChunk
	}
	mock.lockShouldBeStored.RLock()
	calls = mock.calls.ShouldBeStored
	mock.lockShouldBeStored.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *DocumentChunkRepoerMock) Update(ctx context.Context, chunk *model.DocumentChunk) error {
	if mock.UpdateFunc == nil {
		panic("DocumentChunkRepoerMock.UpdateFunc: method is nil but DocumentChunkRepoer.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Chunk *model.DocumentChunk
	}{
		Ctx:   ctx,
		Chunk: chunk,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, chunk)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.UpdateCalls())
func (mock *DocumentChunkRepoerMock) UpdateCalls() []struct {
	Ctx   context.Context
	Chunk *model.DocumentChunk
} {
	var calls []struct {
		Ctx   context.Context
		Chunk *model.DocumentChunk
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *DocumentChunkRepoerMock) WithTx(ctx context.Context, fn func(data.DocumentChunkRepoer) error) error {
	if mock.WithTxFunc == nil {
		panic("DocumentChunkRepoerMock.WithTxFunc: method is nil but DocumentChunkRepoer.WithTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(data.DocumentChunkRepoer) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(ctx, fn)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.WithTxCalls())
func (mock *DocumentChunkRepoerMock) WithTxCalls() []struct {
	Ctx context.Context
	Fn  func(data.DocumentChunkRepoer) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(data.DocumentChunkRepoer) error
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
