// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atomic_knowledge.sql

package db

import (
	"time"

	"github.com/google/uuid"
)

type CreateAtomicKnowledgeBatchParams struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DocumentID         uuid.UUID
	DocumentChunkID    uuid.UUID
	TruthTier          int32
	Topics             []string
	Subject            string
	Predicate          string
	Object             string
	Note               string
	MarkedAsInvalid    bool
	MarkedAsIrrelevant bool
}
