// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_message.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentConversationMessages = `-- name: GetRecentConversationMessages :many
SELECT id, jid, role, content, phone_number, country_code, created_at FROM conversation_messages
WHERE jid = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentConversationMessagesParams struct {
	Jid   string
	Limit int32
}

func (q *Queries) GetRecentConversationMessages(ctx context.Context, arg GetRecentConversationMessagesParams) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, getRecentConversationMessages, arg.Jid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMessage
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.Jid,
			&i.Role,
			&i.Content,
			&i.PhoneNumber,
			&i.CountryCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConversationMessage = `-- name: InsertConversationMessage :one
INSERT INTO conversation_messages (
    jid, role, content, phone_number, country_code
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, created_at
`

type InsertConversationMessageParams struct {
	Jid         string
	Role        string
	Content     string
	PhoneNumber pgtype.Text
	CountryCode pgtype.Text
}

type InsertConversationMessageRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertConversationMessage(ctx context.Context, arg InsertConversationMessageParams) (InsertConversationMessageRow, error) {
	row := q.db.QueryRow(ctx, insertConversationMessage,
		arg.Jid,
		arg.Role,
		arg.Content,
		arg.PhoneNumber,
		arg.CountryCode,
	)
	var i InsertConversationMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
