// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateDocumentChunksBatch implements pgx.CopyFromSource.
type iteratorForCreateDocumentChunksBatch struct {
	rows                 []CreateDocumentChunksBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateDocumentChunksBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateDocumentChunksBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
		r.rows[0].DocumentID,
		r.rows[0].SequenceNumber,
		r.rows[0].Topics,
		r.rows[0].FactualityScore,
		r.rows[0].Text,
		r.rows[0].Page,
		r.rows[0].Chapter,
		r.rows[0].LayoutType,
		r.rows[0].BoundingBox,
		r.rows[0].AssetUrl,
	}, nil
}

func (r iteratorForCreateDocumentChunksBatch) Err() error {
	return nil
}

func (q *Queries) CreateDocumentChunksBatch(ctx context.Context, arg []CreateDocumentChunksBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"document_chunks"}, []string{"id", "created_at", "updated_at", "document_id", "sequence_number", "topics", "factuality_score", "text", "page", "chapter", "layout_type", "bounding_box", "asset_url"}, &iteratorForCreateDocumentChunksBatch{rows: arg})
}
