// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: influencer.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInfluencerByUsername = `-- name: GetInfluencerByUsername :one
SELECT id, platform, username, profile_url, nickname, bio, avatar_url, verified, followers_count, following_count, hearts_count, reported_video_count, tracked_video_count, source, discovered_via_keyword, discovered_from_video_url, first_video_at, last_video_at, avg_upload_interval_hours, last_checked_at, created_at, updated_at FROM influencers WHERE platform = $1 AND username = $2 LIMIT 1
`

type GetInfluencerByUsernameParams struct {
	Platform string
	Username string
}

func (q *Queries) GetInfluencerByUsername(ctx context.Context, arg GetInfluencerByUsernameParams) (Influencer, error) {
	row := q.db.QueryRow(ctx, getInfluencerByUsername, arg.Platform, arg.Username)
	var i Influencer
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Username,
		&i.ProfileUrl,
		&i.Nickname,
		&i.Bio,
		&i.AvatarUrl,
		&i.Verified,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.HeartsCount,
		&i.ReportedVideoCount,
		&i.TrackedVideoCount,
		&i.Source,
		&i.DiscoveredViaKeyword,
		&i.DiscoveredFromVideoUrl,
		&i.FirstVideoAt,
		&i.LastVideoAt,
		&i.AvgUploadIntervalHours,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInfluencers = `-- name: ListInfluencers :many
SELECT id, platform, username, profile_url, nickname, bio, avatar_url, verified, followers_count, following_count, hearts_count, reported_video_count, tracked_video_count, source, discovered_via_keyword, discovered_from_video_url, first_video_at, last_video_at, avg_upload_interval_hours, last_checked_at, created_at, updated_at FROM influencers ORDER BY username
`

func (q *Queries) ListInfluencers(ctx context.Context) ([]Influencer, error) {
	rows, err := q.db.Query(ctx, listInfluencers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Influencer
	for rows.Next() {
		var i Influencer
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Username,
			&i.ProfileUrl,
			&i.Nickname,
			&i.Bio,
			&i.AvatarUrl,
			&i.Verified,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.HeartsCount,
			&i.ReportedVideoCount,
			&i.TrackedVideoCount,
			&i.Source,
			&i.DiscoveredViaKeyword,
			&i.DiscoveredFromVideoUrl,
			&i.FirstVideoAt,
			&i.LastVideoAt,
			&i.AvgUploadIntervalHours,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInfluencerAggregates = `-- name: UpdateInfluencerAggregates :exec
UPDATE influencers
SET
    first_video_at = $1,
    last_video_at = $2,
    avg_upload_interval_hours = $3,
    tracked_video_count = $4,
    last_checked_at = NOW(),
    updated_at = NOW()
WHERE id = $5
`

type UpdateInfluencerAggregatesParams struct {
	FirstVideoAt           pgtype.Timestamptz
	LastVideoAt            pgtype.Timestamptz
	AvgUploadIntervalHours pgtype.Float8
	TrackedVideoCount      int64
	ID                     uuid.UUID
}

func (q *Queries) UpdateInfluencerAggregates(ctx context.Context, arg UpdateInfluencerAggregatesParams) error {
	_, err := q.db.Exec(ctx, updateInfluencerAggregates,
		arg.FirstVideoAt,
		arg.LastVideoAt,
		arg.AvgUploadIntervalHours,
		arg.TrackedVideoCount,
		arg.ID,
	)
	return err
}

const upsertInfluencer = `-- name: UpsertInfluencer :one
INSERT INTO influencers (
    platform, username, profile_url, nickname, bio, avatar_url, verified,
    followers_count, following_count, hearts_count, reported_video_count,
    source, discovered_via_keyword, discovered_from_video_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (platform, username) DO UPDATE SET
    profile_url = EXCLUDED.profile_url,
    nickname = EXCLUDED.nickname,
    bio = EXCLUDED.bio,
    avatar_url = EXCLUDED.avatar_url,
    verified = EXCLUDED.verified,
    followers_count = EXCLUDED.followers_count,
    following_count = EXCLUDED.following_count,
    hearts_count = EXCLUDED.hearts_count,
    reported_video_count = EXCLUDED.reported_video_count,
    updated_at = NOW()
RETURNING id, created_at, updated_at
`

type UpsertInfluencerParams struct {
	Platform               string
	Username               string
	ProfileUrl             string
	Nickname               string
	Bio                    string
	AvatarUrl              string
	Verified               bool
	FollowersCount         int64
	FollowingCount         int64
	HeartsCount            int64
	ReportedVideoCount     int64
	Source                 string
	DiscoveredViaKeyword   pgtype.Text
	DiscoveredFromVideoUrl pgtype.Text
}

type UpsertInfluencerRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertInfluencer(ctx context.Context, arg UpsertInfluencerParams) (UpsertInfluencerRow, error) {
	row := q.db.QueryRow(ctx, upsertInfluencer,
		arg.Platform,
		arg.Username,
		arg.ProfileUrl,
		arg.Nickname,
		arg.Bio,
		arg.AvatarUrl,
		arg.Verified,
		arg.FollowersCount,
		arg.FollowingCount,
		arg.HeartsCount,
		arg.ReportedVideoCount,
		arg.Source,
		arg.DiscoveredViaKeyword,
		arg.DiscoveredFromVideoUrl,
	)
	var i UpsertInfluencerRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
