// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: influencer_video.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listInfluencerVideosByInfluencerID = `-- name: ListInfluencerVideosByInfluencerID :many
SELECT id, influencer_id, tiktok_video_id, video_url, caption, like_count, comment_count, share_count, play_count, collect_count, hashtags, video_created_at, created_at, updated_at FROM influencer_videos WHERE influencer_id = $1 ORDER BY video_created_at ASC
`

func (q *Queries) ListInfluencerVideosByInfluencerID(ctx context.Context, influencerID uuid.UUID) ([]InfluencerVideo, error) {
	rows, err := q.db.Query(ctx, listInfluencerVideosByInfluencerID, influencerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InfluencerVideo
	for rows.Next() {
		var i InfluencerVideo
		if err := rows.Scan(
			&i.ID,
			&i.InfluencerID,
			&i.TiktokVideoID,
			&i.VideoUrl,
			&i.Caption,
			&i.LikeCount,
			&i.CommentCount,
			&i.ShareCount,
			&i.PlayCount,
			&i.CollectCount,
			&i.Hashtags,
			&i.VideoCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInfluencerVideo = `-- name: UpsertInfluencerVideo :one
INSERT INTO influencer_videos (
    influencer_id, tiktok_video_id, video_url, caption,
    like_count, comment_count, share_count, play_count, collect_count,
    hashtags, video_created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (tiktok_video_id) DO UPDATE SET
    like_count = EXCLUDED.like_count,
    comment_count = EXCLUDED.comment_count,
    share_count = EXCLUDED.share_count,
    play_count = EXCLUDED.play_count,
    collect_count = EXCLUDED.collect_count,
    updated_at = NOW()
RETURNING id, created_at, updated_at, (xmax = 0)::boolean AS is_new
`

type UpsertInfluencerVideoParams struct {
	InfluencerID   uuid.UUID
	TiktokVideoID  string
	VideoUrl       string
	Caption        string
	LikeCount      int64
	CommentCount   int64
	ShareCount     int64
	PlayCount      int64
	CollectCount   int64
	Hashtags       []string
	VideoCreatedAt time.Time
}

type UpsertInfluencerVideoRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	IsNew     bool
}

func (q *Queries) UpsertInfluencerVideo(ctx context.Context, arg UpsertInfluencerVideoParams) (UpsertInfluencerVideoRow, error) {
	row := q.db.QueryRow(ctx, upsertInfluencerVideo,
		arg.InfluencerID,
		arg.TiktokVideoID,
		arg.VideoUrl,
		arg.Caption,
		arg.LikeCount,
		arg.CommentCount,
		arg.ShareCount,
		arg.PlayCount,
		arg.CollectCount,
		arg.Hashtags,
		arg.VideoCreatedAt,
	)
	var i UpsertInfluencerVideoRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsNew,
	)
	return i, err
}
