// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Document struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	IngestedAt      pgtype.Timestamptz
	FileKey         string
	Sha256          string
	Title           string
	Filename        string
	Filetype        string
	Filesize        int64
	PageCount       int32
	PublisherName   string
	PublicationYear int32
}

type DocumentChunk struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DocumentID      uuid.UUID
	SequenceNumber  int32
	Topics          []string
	FactualityScore float64
	Text            string
	Page            int32
	Chapter         string
	LayoutType      string
	BoundingBox     []float64
	AssetUrl        string
	Embedding       *pgvector_go.Vector
}

type User struct {
	ID        int32
	Email     string
	CreatedAt pgtype.Timestamp
}
