// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	IngestedAt      pgtype.Timestamptz
	FileKey         string
	Sha256          string
	Title           string
	Filename        string
	Filetype        string
	Filesize        int64
	PageCount       int32
	PublisherName   string
	PublicationYear int32
}

type User struct {
	ID        int32
	Email     string
	CreatedAt pgtype.Timestamp
}
