// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Email     string
	CreatedAt pgtype.Timestamp
}

type Video struct {
	ID                uuid.UUID
	VideoUrl          string
	AuthorUsername    string
	AuthorProfileUrl  string
	Caption           pgtype.Text
	PlayCount         pgtype.Int8
	LikeCount         pgtype.Int8
	ThumbnailUrl      string
	LocationCreated   pgtype.Text
	VideoCreatedAt    pgtype.Timestamptz
	TranscriptionText pgtype.Text
	VideoType         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
