// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: video_queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideos = `-- name: CreateVideos :one
INSERT INTO videos (
    video_url, 
    author_username, 
    author_profile_url, 
    caption,
    play_count, 
    like_count, 
    thumbnail_url, 
    location_created,
    video_created_at, 
    video_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (video_url) DO UPDATE SET
    play_count = EXCLUDED.play_count,
    like_count = EXCLUDED.like_count,
    updated_at = NOW()
RETURNING id, created_at, updated_at
`

type CreateVideosParams struct {
	VideoUrl         string
	AuthorUsername   string
	AuthorProfileUrl string
	Caption          pgtype.Text
	PlayCount        pgtype.Int8
	LikeCount        pgtype.Int8
	ThumbnailUrl     string
	LocationCreated  pgtype.Text
	VideoCreatedAt   pgtype.Timestamptz
	VideoType        string
}

type CreateVideosRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateVideos(ctx context.Context, arg CreateVideosParams) (CreateVideosRow, error) {
	row := q.db.QueryRow(ctx, createVideos,
		arg.VideoUrl,
		arg.AuthorUsername,
		arg.AuthorProfileUrl,
		arg.Caption,
		arg.PlayCount,
		arg.LikeCount,
		arg.ThumbnailUrl,
		arg.LocationCreated,
		arg.VideoCreatedAt,
		arg.VideoType,
	)
	var i CreateVideosRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateVideoTranscription = `-- name: UpdateVideoTranscription :exec
UPDATE videos
SET 
    transcription_text = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateVideoTranscriptionParams struct {
	TranscriptionText pgtype.Text
	ID                uuid.UUID
}

func (q *Queries) UpdateVideoTranscription(ctx context.Context, arg UpdateVideoTranscriptionParams) error {
	_, err := q.db.Exec(ctx, updateVideoTranscription, arg.TranscriptionText, arg.ID)
	return err
}
